# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/axi_lite.xdc

# Block Designs: bd/axi_lite/axi_lite.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite || ORIG_REF_NAME==axi_lite} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_processing_system7_0_0/axi_lite_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_processing_system7_0_0 || ORIG_REF_NAME==axi_lite_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_vga_module_0_0/axi_lite_vga_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_vga_module_0_0 || ORIG_REF_NAME==axi_lite_vga_module_0_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_par2ser_0_0/axi_lite_par2ser_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_par2ser_0_0 || ORIG_REF_NAME==axi_lite_par2ser_0_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_par2ser_1_0/axi_lite_par2ser_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_par2ser_1_0 || ORIG_REF_NAME==axi_lite_par2ser_1_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_par2ser_2_0/axi_lite_par2ser_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_par2ser_2_0 || ORIG_REF_NAME==axi_lite_par2ser_2_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_par2ser_3_0/axi_lite_par2ser_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_par2ser_3_0 || ORIG_REF_NAME==axi_lite_par2ser_3_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_encode_0_0/axi_lite_encode_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_encode_0_0 || ORIG_REF_NAME==axi_lite_encode_0_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_encode_1_0/axi_lite_encode_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_encode_1_0 || ORIG_REF_NAME==axi_lite_encode_1_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_encode_2_0/axi_lite_encode_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_encode_2_0 || ORIG_REF_NAME==axi_lite_encode_2_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_clk_wiz_0_0/axi_lite_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_clk_wiz_0_0 || ORIG_REF_NAME==axi_lite_clk_wiz_0_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_xlconstant_0_0/axi_lite_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_xlconstant_0_0 || ORIG_REF_NAME==axi_lite_xlconstant_0_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_xlconstant_1_0/axi_lite_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_xlconstant_1_0 || ORIG_REF_NAME==axi_lite_xlconstant_1_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_m_axi_lite_0_1/axi_lite_m_axi_lite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_m_axi_lite_0_1 || ORIG_REF_NAME==axi_lite_m_axi_lite_0_1} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_ps7_0_axi_periph_1/axi_lite_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_ps7_0_axi_periph_1 || ORIG_REF_NAME==axi_lite_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_rst_ps7_0_50M_1/axi_lite_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_rst_ps7_0_50M_1 || ORIG_REF_NAME==axi_lite_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_xlconstant_2_0/axi_lite_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_xlconstant_2_0 || ORIG_REF_NAME==axi_lite_xlconstant_2_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_ila_0_0/axi_lite_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_ila_0_0 || ORIG_REF_NAME==axi_lite_ila_0_0} -quiet] -quiet

# IP: bd/axi_lite/ip/axi_lite_auto_pc_0/axi_lite_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_lite_auto_pc_0 || ORIG_REF_NAME==axi_lite_auto_pc_0} -quiet] -quiet

# XDC: bd/axi_lite/axi_lite_ooc.xdc
